model:
  K:
    - 10
    - 25
#    - 50
#    - 75
#    - 100
training:
  lr:
    - 0.008
  epochs:
    - 1000
  normalize_and_log:
    - false
  reference_leiden_clustering_resolution: 3.0
#sc_embedding:
#  method: pca
#  d: 32
loss_weights:
  - lambda_rec_spot: 0.5
    lambda_rec_gene: 0.5
#    lambda_clust_intra: 0
#    lambda_clust_inter: 0
    lambda_state_entropy: 0.1
    lambda_spot_entropy: 0.08
    lambda_soft_contingency: 1
